### PR TITLE
Keep submodules open on low-width devices. 

### LINKED ISSUE #18: Make Drop Down Menu + Responsiveness Work
Twitter Bootstrap, the nav menu  collapses with media queries.
Clicking on the nav icon, expands the menu, but not the subnav - and thus there is never a subnav in mobile.

I tried a LOT Of things to get around this, in part it might be because the top menu items are also links (vrs just clicks)  .  Similar topic here:  http://stackoverflow.com/questions/11926028/bootstrap-dropdown-in-collapse   but we are looking at bootstrap 3

For now I have set responsive to 1px to avoid this problem, but of course all that means now is you can see the menu in mobile, but there's no mobile view :S 

need to figure out how to make sub menu display for responsive mode.

You can see the media variables I changed here:   https://github.com/emmairwin/mozilla-community-edu/commit/dbfa6f9b863bc5b4c132907006b53808992279e3

### PR DESCRIPTION
**Pull request by asdofindia**
Fixes #18 

Initially I was trying to get css hover working. It got slightly complicated. So what I've done now is to replicate the desktop behavior on mobile. That is, the submodules of the active module will stay open in small resolutions.

The ideal solution is to show submodules on hover in desktop and on clicking the caret in mobile. This could be tried later with http://stackoverflow.com/a/28686737 (by keeping the caret in a separate anchor that is toggle for the dropdown) or http://stackoverflow.com/a/28703557 (by opening submenu on first click, and following link on second click)

### CODE REVIEW

**Comment by emmairwin** [comment]
Hey thanks for this - I am going to quickly take a look at how this runs locally, and get back to you.  Thanks so much for your time!

**Comment by asdofindia** [comment]
Here're some screenshots.

screenshot from 2015-04-10 03 03 45
screenshot from 2015-04-10 03 03 57
screenshot from 2015-04-10 03 04 07

**Comment by emmairwin** [comment]
@asdofindia asdofindia  that looks amazing, you have no idea how long I tried to make this work.  I am still going to do a test locally, since pull request automatically goes to live site (github pages), but I WILL do this by tomorrow and update you.  Thanks  you rock!

**Comment by emmairwin** [comment]
So yay!  This looks great  The only issues I see we need to fix is this weird double arrow that shows up:
doublearrow

I'm going to open a new issue for usability  for responsive menu in that we need to make 4 clicks to get to a sub menu item.   

But awesome work thanks so much!

**Comment by emmairwin** [comment]
oh by the way re: hover. I also tried that but then found out of course that android doesn't support hover as an action. it then treated hovers as clicks, which meant the sub menu was never clickable :S

**Comment by emmairwin** [comment]
@asdofindia do you have a Mozillians Profile? I was looking to add you to our Community education team page - as a code contributor, but can't find you

**Comment by asdofindia** [comment]
Yes, I do : https://mozillians.org/en-US/u/asdofindia/

**Comment by emmairwin** [comment]
@asdofindia I vouched you - and added you to our team page, hope that's OK:  http://education.mozilla-community.org/modules/about/team/

**Comment by asdofindia** [comment]
Of course! Thanks for the vouch and that lovely vouch note.

**Pull request merged**
